// <auto-generated />
namespace MyMacroCounter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11122015_Macro_Sub_Types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11122015_Macro_Sub_Types));
        
        string IMigrationMetadata.Id
        {
            get { return "201512110637430_11122015_Macro_Sub_Types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
